#!/bin/ksh 
###### 09/15/2025 ######################################################
# Calculate HGEFS Ensemble Probability Forecast, Ensemble Mean & Spread
########################################################################

set -xa

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hgefs}
export RUN=${RUN:-hgefs}

export PS4='+ $SECONDS + '
date

########################################################
# obtain unique process id (pid) and make temp directory
########################################################
export pid=$$
#export DATAROOT=${DATAROOT:-/lfs/f1/ops/${envir}/tmp}
export DATA=$DATAROOT/${job}.${pid}
#export DATA=${DATA:-${DATAROOT:?}/${pid}}

mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

##################
# File To Log Msgs
##################

export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

#####################################
# Determine Job Output Name on System
#####################################
export outid="LL$job"
#export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

##############################################################
# SENDCOM=YES--Copy output file to ${COMROOT}
# SENDECF=YES--Allow to talk back to SMS
# SENDDBN=YES--Alert output file to TOC, set to NO for testing
##############################################################

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}    
export SENDECF=${SENDECF:-YES}

######################################################################
# IFHYBRID  - Generate Products from AIGEFS and GEFS Combined Ensemble
######################################################################
export IFHYBRID=YES

#########################
# Specify Execution Areas
#########################
 
export HOMEhgefs=${HOMEhgefs:-${PACKAGEROOT}/hgefs.${hgefs_ver}}
export EXEChgefs=${EXEChgefs:-$HOMEhgefs/exec}
export FIXhgefs=${FIXhgefs:-$HOMEhgefs/fix}
export USHhgefs=${USHhgefs:-$HOMEhgefs/ush}

#export ERRSCRIPT=err_chk
#export REDOUT='1>>'
#export REDERR='2>'

#########################################
# Run setpdy and initialize PDY variables
#########################################
setpdy.sh
. ./PDY

########################
# Define COM directories
########################

#CMD - COMIN will need to be fixed when aigefs_forecast com structure is updated

export COMIN_AIGEFS=${COMIN_AIGEFS:-$(compath.py ${envir}/com/aigefs/${aigefs_ver}/aigefs.${PDY}/${cyc}/model)}
export COMIN_GEFS=${COMIN_GEFS:-$(compath.py ${envir}/com/gefs/${gefs_ver}/gefs.${PDY}/${cyc}/atmos)}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${hgefs_ver}/$RUN.${PDY}/${cyc}/products/ensstat)}

mkdir -m 775 -p ${COMOUT}

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#####################
# Execute the scripts
#####################

$HOMEhgefs/scripts/exhgefs_ensstat.sh                  

cat $DATA/$pgmout.120_avgspr_pres
cat $DATA/$pgmout.240_avgspr_pres
cat $DATA/$pgmout.120_avgspr_sfc 
cat $DATA/$pgmout.240_avgspr_sfc

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

########################################
# Remove the Temporary working directory
########################################
if [ $KEEPDATA != YES ]; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
