#!/bin/ksh 
###### 09/15/2025 ######################################################
# Calculate HGEFS Ensemble Probability Forecast, Ensemble Mean & Spread
########################################################################

set -xa

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hgefs}
export RUN=${RUN:-hgefs}

export PS4='+ $SECONDS + '
date

########################################################
# obtain unique process id (pid) and make temp directory
########################################################
export job=${job:-$NET}
export jobid=${jobid:-$$}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}

mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

#########################################
# Run setpdy and initialize PDY variables
#########################################
setpdy.sh
. ./PDY

#####################################
# Determine Job Output Name on System
#####################################
export pgmout="OUTPUT.$$"

##############################################################
# SENDCOM=YES--Copy output file to ${COMROOT}
# SENDECF=YES--Allow to talk back to SMS
# SENDDBN=YES--Alert output file to TOC, set to NO for testing
##############################################################

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}    
export SENDECF=${SENDECF:-YES}

######################################################################
# IFHYBRID  - Generate Products from AIGEFS and GEFS Combined Ensemble
######################################################################
export IFHYBRID=YES

#########################
# Specify Execution Areas
#########################
 
export EXEChgefs=${EXEChgefs:-$HOMEhgefs/exec}

########################
# Define COM directories
########################

export COMINaigefs=${COMINaigefs:-$(compath.py ${envir}/aigefs/${aigefs_ver})}/aigefs.${PDY}/${cyc}
export COMINgefs=${COMINgefs:-$(compath.py ${envir}/gefs/${gefs_ver})}/gefs.${PDY}/${cyc}/atmos
export COMOUT=${COMOUT:-$(compath.py -o $NET/${hgefs_ver}/$RUN.${PDY})}/${cyc}/ensstat/products/atmos/grib2

mkdir -m 775 -p ${COMOUT}

msg="JOB $job HAS BEGUN on `hostname`"
postmsg "$msg"

env

#####################
# Execute the scripts
#####################

$HOMEhgefs/scripts/exhgefs_ensstat.sh
export err=$?; err_chk "$job failed while running $HOMEhgefs/scripts/exhgefs_ensstat.sh"

msg="JOB $job HAS COMPLETED NORMALLY"
postmsg "$msg"

if [ -e $pgmout ]; then
  cat $pgmout
fi
if [ -e errfile ]; then
  cat errfile
fi

########################################
# Remove the Temporary working directory
########################################
if [ $KEEPDATA != YES ]; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
